---
- name: Query source SRC_DHCP_ID
  ansible.builtin.command: >
    {{ neutron_namespace_drain_venv }}/bin/openstack
    network agent list --host {{ neutron_namespace_drain_host }}
    --agent-type dhcp -f value -c ID
  register: src_dhcp_id
  environment: "{{ openstack_auth_env }}"
  changed_when: false
  delegate_to: "{{ neutron_namespace_play_host }}"
  vars:
    ansible_host: "{{ hostvars[neutron_namespace_play_host].ansible_host }}"

- name: Enable DHCP agent
  ansible.builtin.command: >
    {{ neutron_namespace_drain_venv }}/bin/openstack
    network agent set "{{ src_dhcp_id.stdout }}" --enable
  environment: "{{ openstack_auth_env }}"
  changed_when: false
  delegate_to: "{{ neutron_namespace_play_host }}"
  vars:
    ansible_host: "{{ hostvars[neutron_namespace_play_host].ansible_host }}"

- name: Get Network IDs
  ansible.builtin.command: >
    {{ neutron_namespace_drain_venv }}/bin/openstack
    network list -f value -c ID
  register: network_ids
  environment: "{{ openstack_auth_env }}"
  changed_when: false
  delegate_to: "{{ neutron_namespace_play_host }}"
  vars:
    ansible_host: "{{ hostvars[neutron_namespace_play_host].ansible_host }}"

- name: Add DHCP agent
  ansible.builtin.command: >
    {{ neutron_namespace_drain_venv }}/bin/openstack
    network agent add network {{ src_dhcp_id.stdout }} {{ item }} --dhcp
  environment: "{{ openstack_auth_env }}"
  changed_when: false
  delegate_to: "{{ neutron_namespace_play_host }}"
  vars:
    ansible_host: "{{ hostvars[neutron_namespace_play_host].ansible_host }}"
  with_items:
    - "{{ network_ids.stdout_lines }}"
  loop_control:
    pause: 10
