---
name: Tests

# Controls when the action will run.
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - "2.10"
          - "2.12"
          - "2.14"
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so it's accessible to the job
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [[ "${{ matrix.ansible }}" = "2.10" ]]; then
              ansible_package=ansible-base
          else
              ansible_package=ansible-core
          fi
          pip install $ansible_package==${{ matrix.ansible }}.* 'ansible-lint==5.*'

      - name: Linting code
        run: |
          ansible-lint -v --force-color

  sanity:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ansible:
          - "2.10"
          - "2.12"
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so it's accessible to the job
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          # Ansible 2.10 supports up to Python 3.8.
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [[ "${{ matrix.ansible }}" = "2.10" ]]; then
              ansible_package=ansible-base
          else
              ansible_package=ansible-core
          fi
          pip install $ansible_package==${{ matrix.ansible }}.*

      - name: Running sanity tests
        run: |
          .github/workflows/sanity.sh
